---
title: "Identyfikacja docelowych odbiorców pożyczki"
output:
  rmdformats::material:
    highlight: kate
    self_contained: false
    thumbnails: false
    lightbox: true
    gallery: true
    cards: false
    use_bookdown: false
    fig_caption: false
    number_sections: true
always_allow_html: true
---



```{r setup, include=FALSE}
# Enable error display - don't stop on first error
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, error = TRUE)
knitr::opts_chunk$set(fig.width = 6, fig.height = 4)

# Increase error context for better debugging
options(error = function() {
  cat("\n=== DETAILED ERROR INFORMATION ===\n")
  print(traceback(5))
  cat("====================================\n")
})

# Ustaw mirror CRAN aby zapewnić, że instalacja pakietów działa
options(repos = c(CRAN = "https://cloud.r-project.org"))

# ========== CACHE CONTROL - ZMIEŃ NA TRUE BY WŁĄCZYĆ CACHE ==========
cache_models <- TRUE  # Cache dla models.Rmd (stepwise, logistic regression)
cache_ggstats <- TRUE  # Cache dla ggstatsplot w analiza_statystyczna.Rmd
# =====================================================================

# Użyj pakietu here aby ustalić katalog główny projektu (gdzie znajduje się plik .Rproj)
# Zapewnia to spójny katalog roboczy we wszystkich sekcjach
if (!requireNamespace("here", quietly = TRUE)) {
  install.packages("here", repos = "https://cloud.r-project.org")
}
library(here)

# Ustaw katalog roboczy na katalog główny projektu
setwd(here::here())

# Wykresy wyśrodkowane
knitr::opts_chunk$set(fig.align = "center")
```

```{css, echo=FALSE}
/* Wszystkie podrozdziały w menu nawigacji, nie byłem w stanie tego zrobić inaczej niż edytowanie css-a. */
#toc > ul li ul li {
  max-height: none !important;
  overflow: visible !important;
}
/* globalna czcionka */
body, html {
  font-family: "Lato", "Arial", sans-serif !important;
}

h1, h2, h3, h4, h5, h6 {
  font-family: "Lato", "Arial", sans-serif !important;
}
```

```{r child_intro, child = 'sections/intro.Rmd'}
```


```{r child_missing_data, child = 'sections/missing_data_analysis.Rmd'}
```


```{r child_visualizations, child = 'sections/visualizations.Rmd'}
```

```{r child_analiza_statystyczna, child = 'sections/analiza_statystyczna.Rmd'}
```

```{r child_models, child = 'sections/models.Rmd'}
```

```{r child_outro, child = 'sections/outro.Rmd'}
```
