# **Wprowadzenie**

Studium przypadku „Kredyty - Identyfikacja docelowych odbiorców
pożyczki” koncentruje się na analizie ryzyka w procesie udzielania
finansowania klientom. Wykorzystując techniki eksploracyjnej analizy
danych (EDA), projekt ma na celu zrozumienie, w jaki sposób cechy
konsumentów oraz parametry pożyczek wpływają na prawdopodobieństwo
terminowej spłaty zobowiązań.

Firmy udzielające pożyczek stoją przed podwójnym wyzwaniem: z jednej
strony ryzykują utratę potencjalnych zysków, jeśli odrzucą wnioski
klientów zdolnych do spłaty, z drugiej - mogą ponieść straty finansowe,
jeśli zaakceptują wnioski osób, które nie wywiążą się ze zobowiązań.
Dlatego kluczowe jest zidentyfikowanie zmiennych, które są silnymi
wskaźnikami niewypłacalności. W związku z tym niniejsze studium przypadku stawia następujące pytania badawcze:

-	Czy wysokość kwoty kredytu wpływa na prawdopodobieństwo odmowy, anulowania lub niewykorzystania oferty?

-	W jaki sposób status kontraktu (zatwierdzony, anulowany, odmowa, niewykorzystana oferta) odzwierciedla potencjalne trudności klienta ze spłatą rat?

-	Czy istnieją wzorce w danych dotyczące liczby rat lub harmonogramu spłat, które mogą sygnalizować ryzyko problemów ze spłatą?

-	Jakie kombinacje czynników (np. kwota kredytu + typ klienta + status kontraktu) najlepiej przewidują trudności ze spłatą?


### Dane

W niniejszym projekcie wykorzystane zostaną dane z pliku
„previous_application_new.csv”, zawierającego informacje o decyzjach
kredytowych (zatwierdzone, anulowane, odrzucone, niewykorzystane), oraz
słownik zmiennych „opis_zmiennych.xlsx”, który ułatwi interpretację
atrybutów. Analiza pozwoli wskazać wzorce zachowań klientów i czynniki
ryzyka, które mogą wspierać proces podejmowania decyzji kredytowych.

### Użyte biblioteki

Podczas analizy użyto następujących bibliotek:

```{r zaladuj_biblioteki, message=FALSE}
library(readr)
library(gt)
library(tidyverse)
library(naniar)
library(VIM)
library(ggplot2)
library(kableExtra)
library(dplyr)
library(tidyr)
library(corrplot)
library(ggstatsplot)
library(plotly)
library(dplyr)
library(forcats)
library(corrplot)
library(networkD3)
library(scales)
```